import i18next from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

i18next
  .use(initReactI18next)
  .use(LanguageDetector)
  .init({
    fallbackLng: "en",
    resources: {
      en: {
        translation: {
          headerText: `Designed with ❤ in Rocketseat's NLW`,
          footerText:
            "Tip: you can use the <0>{ {{key}} }</0> variable in your prompt to add the transcript content of the selected video",
          languagePlaceholder: "Language",
          transcriptionPromptTitle: "Transcription prompt",
          transcriptionPromptPlaceholder:
            "Include keywords mentioned in the video separated by commas (,)",
          videoSelect: "Select a video",
          videoSubmit: "Upload video",
          promptTitle: "Prompt",
          promptPlaceholder: "Select a prompt...",
          modelTitle: "AI Model",
          modelTip: "You will be able to customize this option soon",
          temperatureTitle: "Temperature",
          temperatureTip:
            "Higher values tend to make the result more creative, but with potential errors",
          submit: "Execute",
          aiPromptPlaceholder: "Include the prompt for the AI...",
          aiResultPlaceholder: "Result generated by the AI...",
          status: {
            downloading: "Downloading...",
            converting: "Converting...",
            uploading: "Uploading...",
            generating: "Generating...",
            success: "Success!",
          },
        },
      },
      pt: {
        translation: {
          headerText: "Desenvolvido com ❤ no NLW da Rocketseat",
          footerText:
            "Lembre-se: você pode utilizar a variável <0>{ {{key}} }</0> no seu prompt para adicionar o conteúdo da transcrição do vídeo selecionado",
          languagePlaceholder: "Idioma",
          transcriptionPromptTitle: "Prompt da descrição",
          transcriptionPromptPlaceholder:
            "Inclua palavras-chave mencionadas no vídeo separadas por vírgula (,)",
          videoSelect: "Selecione um vídeo",
          videoSubmit: "Carregar vídeo",
          promptTitle: "Prompt",
          promptPlaceholder: "Selecione um prompt...",
          modelTitle: "Modelo IA",
          modelTip: "Você poderá customizar essa opção em breve",
          temperatureTitle: "Temperatura",
          temperatureTip:
            "Valores mais altos tendem a deixar o resultado mais criativo e com possíveis erros",
          submit: "Executar",
          aiPromptPlaceholder: "Inclua o prompt para a IA...",
          aiResultPlaceholder: "Resultado gerado pela IA...",
          status: {
            downloading: "Downloading...",
            converting: "Convertendo...",
            uploading: "Carregando...",
            generating: "Transcrevendo...",
            success: "Sucesso!",
          },
        },
      },
    },
  });
